server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
    schema: classpath:schema.sql
    initialization-mode: always
  jpa:
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE